name: Vercel Preview Deployment

on:
  pull_request:
    paths:
      - 'packages/nextjs/**'
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Dump org id
        run: echo -n "${{ secrets.VERCEL_ORG_ID }}" | xxd -ps
      - name: Dump project
        run: echo -n "${{ secrets.VERCEL_PROJECT_ID  }}" | xxd -ps

      - name: Dump token
        run: echo -n "${{ secrets.VERCEL_TOKEN  }}" | xxd -ps

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
